# Academic Performance Prediction

Dataset: `academic_performance_dataset.csv`

## 1. Imports & Setup

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, mean_absolute_error, mean_squared_error, r2_score

## 2. Load & Preview Data

In [25]:
# Load dataset
df = pd.read_csv('academic_performance_dataset.csv')
# print shape of the datase
print("Dataset shape:", df.shape)
#print the head
df.head()

Dataset shape: (1000, 11)

,age,study_hours,attendance_rate,assignments_submitted,parental_support,internet_access,gender,school_type,extracurricular_hours,sleep_hours,final_grade
0,19.0,12.606539,99.932696,0.0,1.0,1.0,Female,Private,4.675619,9.710850,4.656857
1,15.0,1.081419,97.223448,NaN,1.0,1.0,Female,Private,6.494556,6.488781,1.463881
2,17.0,14.880645,50.133550,1.0,4.0,0.0,Male,Private,0.484310,9.298099,13.195475
3,18.0,11.292144,89.768916,9.0,NaN,NaN,Male,Public,NaN,6.689408,24.201369
4,18.0,23.444111,67.680264,4.0,5.0,0.0,Female,Public,8.276423,9.200973,20.357069

## 3. Exploratory Data Analysis (EDA)

In [26]:
# Exploratory Data Analysis
print(df.info())
print(df.describe())
# Missing data visualization

print("\nMissing values:")
print(df.isnull().sum())

# Basic distributions
numeric_cols = df.select_dtypes(include=[np.number]).columns
print(f"\nBasic stats:")
print(df[numeric_cols].describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   age                    912 non-null    float64
 1   study_hours            889 non-null    float64
 2   attendance_rate        888 non-null    float64
 3   assignments_submitted  899 non-null    float64
 4   parental_support       902 non-null    float64
 5   internet_access        899 non-null    float64
 6   gender                 903 non-null    object
 7   school_type            894 non-null    object
 8   extracurricular_hours  898 non-null    float64
 9   sleep_hours            903 non-null    float64
 10  final_grade            1000 non-null   float64
dtypes: float64(9), object(2)
memory usage: 86.1+ KB
None
              age  study_hours  attendance_rate  assignments_submitted  \
count  912.000000   889.000000       888.000000             899.000000
mean    17.661184    15.136340        76.540155               4.522803
std      2.279654     4.907033        14.407530               2.885777
min     14.000000     1.081419        50.015354               0.000000
25%     16.000000    11.909840        64.540526               2.000000
50%     18.000000    15.135053        76.604077               4.000000
75%     20.000000    18.336916        88.998012               7.000000
max     21.000000    29.899273        99.982815               9.000000

       parental_support  internet_access  extracurricular_hours  sleep_hours  \
count        902.000000       899.000000             898.000000   903.000000
mean           3.056541         0.505006               7.627975     7.066490
std            1.400855         0.500253               4.245026     1.725271
min            1.000000         0.000000               0.010121     4.026021
25%            2.000000         0.000000               4.125881     5.592860
50%            3.000000         1.000000               7.874417     7.093059
75%            4.000000         1.000000              11.122728     8.579450
max            5.000000         1.000000              14.994580     9.995606

       final_grade
count  1000.000000
mean     16.846202
std       6.317321
min       0.000000
25%      12.686087
50%      16.919052
75%      21.253647
max      37.797592

Missing values:
age                       88
study_hours              111
attendance_rate          112
assignments_submitted    101
parental_support          98
internet_access          101
gender                    97
school_type              106
extracurricular_hours    102
sleep_hours               97
final_grade                0
dtype: int64

Basic stats:
              age  study_hours  attendance_rate  assignments_submitted  \
count  912.000000   889.000000       888.000000             899.000000
mean    17.661184    15.136340        76.540155               4.522803
std      2.279654     4.907033        14.407530               2.885777
min     14.000000     1.081419        50.015354               0.000000
25%     16.000000    11.909840        64.540526               2.000000
50%     18.000000    15.135053        76.604077               4.000000
75%     20.000000    18.336916        88.998012               7.000000
max     21.000000    29.899273        99.982815               9.000000

       parental_support  internet_access  extracurricular_hours  sleep_hours  \
count        902.000000       899.000000             898.000000   903.000000
mean           3.056541         0.505006               7.627975     7.066490
std            1.400855         0.500253               4.245026     1.725271
min            1.000000         0.000000               0.010121     4.026021
25%            2.000000         0.000000               4.125881     5.592860
50%            3.000000         1.000000               7.874417     7.093059
75%            4.000000         1.000000              11.122728     8.579450
max            5.000000         1.000000              14.994580     9.995606

       final_grade
count  1000.000000
mean     16.846202
std       6.317321
min       0.000000
25%      12.686087
50%      16.919052
75%      21.253647
max      37.797592

## 4. Data Cleaning & Preprocessing

In [19]:
# before defining pipeline we have first to separate features and target
X = df.drop('final_grade', axis=1)
y = df['final_grade']
# then after is to identify numeric and categorical columns  
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns
# Define preprocessing pipeline
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])

## 5. Modeling & Evaluation

In [24]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Modeling
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))])

# train model
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

# evaluation
print(f"\nModel Performance:")
print(f"Grade predictions/RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}")
print(f"R^2 Score: {r2_score(y_test, y_pred):.2f}")

Model Performance:
Grade predictions/RMSE: 5.16
R^2 Score: 0.28